name: Deploy to Azure Container Registry
 
on:
 push:
  branches:
   [ main ]

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: production
  
    defaults:
      run:
        shell: bash
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}
 
    - name: Build the image and push it to ACR
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wimappsacr.azurecr.io/fastapi_todo:${{ github.sha }}
        file: Dockerfile
