name: Azure App Service Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'Deploy to Azure App Service'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    name: 'Deploy to Azure App Service'
    runs-on: ubuntu-latest
    needs: build
    environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
            

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
  
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webappstreamlitwim'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          startup-command: "streamlit run app.py"