name: Azure Container Apps Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_to_azure_container_app:
    name: 'Deploy to Azure Container Apps'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SERVICE_PRINCIPAL }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: wimappdevacr.azurecr.io/streamlit:1.0.0
          acrName: wimappdevacr 
          containerAppName: streamlit-containerapp-wim
          resourceGroup: RG_AppDev
          targetPort: 8501
          location: westeurope

#tes